version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: attdbsch
      DB_USER: adminit
      DB_PASSWORD: Bel@1981
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: attdbsch
      POSTGRES_USER: adminit
      POSTGRES_PASSWORD: Bel@1981
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
